version: '3'

services:
  kafka:
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      - ADVERTISED_PORT=9092
      - ADVERTISED_HOST=kafka
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
  influxdb:
    image: influxdb:1.2.4-alpine
    ports:
      - 8083:8083
      - 8086:8086
      - 2003:2003
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
  grafana:
    image: grafana/grafana:4.3.2
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=1ccl@b2017
  sentinel:
    image: elastest/emp:latest
    links:
      - influxdb
      - kafka
    ports:
      - 9000:9000
    environment:
      - STREAM_ADMINUSER=root
      - STREAM_ADMINPASS=pass1234
      - STREAM_DBENDPOINT=influxdb:8086
      - STREAM_ACCESSURL=localhost:8083
      - STREAM_DBTYPE=influxdb
      - ZOOKEEPER_ENDPOINT=kafka:2181
      - KAFKA_ENDPOINT=kafka:9092
      - TOPIC_CHECK_INTERVAL=30000
    volumes:
      - sentinel:/data
volumes:
  sentinel:
