version: '3'

services:
  kafka:
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      - ADVERTISED_PORT=9092
      - ADVERTISED_HOST=some-fqdn.io or localhost
      - ADVERTISED_LISTENERS=some-fqdn.io or localhost
      - LISTENERS=PLAINTEXT://localhost:9092
  influxdb:
    image: influxdb:1.2.4-alpine
    ports:
      - 8083:8083
      - 8086:8086
      - 2003:2003
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
  grafana:
    image: grafana/grafana:4.6.1
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=1ccl@b2017
  emp:
    image: elastest/emp:0.5.0
    links:
      - influxdb
      - kafka
      - grafana
    ports:
      - 9000:9000
    environment:
      - STREAM_ADMINUSER=root
      - STREAM_ADMINPASS=pass1234
      - STREAM_DBENDPOINT=influxdb:8086
      - STREAM_ACCESSURL=localhost:8083
      - STREAM_DBTYPE=influxdb
      - ZOOKEEPER_ENDPOINT=kafka:2181
      - KAFKA_ENDPOINT=kafka:9092
      - TOPIC_CHECK_INTERVAL=30000
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_URL_GRAFANA=http://localhost:8086
      - GRAFANA_URL=http://grafana:3000
      - GRAFANA_ADMIN=admin
      - GRAFANA_PASSWORD=1ccl@b2017
      - INFLUX_USER=root
      - INFLUX_PASSWORD=pass1234
      - SENTINEL_DB_ENDPOINT=/data/sentinel.db
      - ADMIN_TOKEN=somevalue
      - DASHBOARD_TITLE=elastest
      - DASHBOARD_ENDPOINT=localhost:3000
    volumes:
      - sentinel:/data
volumes:
  sentinel:
