version: '3'

services:
  emp:
    image: elastest/emp:latest
    ports:
      - 9100:9100
    environment:
      - KAFKA_ENDPOINT=some-url:port
      - STREAM_DBENDPOINT=some-url:port
      - STREAM_ACCESSURL=some-fqdn:port
      - ZOOKEEPER_ENDPOINT=some-endpoint:port
      - STREAM_ADMINPASS=some-pass
      - STREAM_ADMINUSER=some-user
