version: '3'

services:
  emp-kafka:
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      - ADVERTISED_PORT=9092
      - ADVERTISED_HOST=emp-kafka
      - ADVERTISED_LISTENERS=emp-kafka
      - LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_HEAP_OPTS="-Xmx256M -Xms128M"
    networks:
      - elastest
  emp-influxdb:
    image: influxdb:1.2.4-alpine
    ports:
      - 8083:8083
      - 8086:8086
      - 2003:2003
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    networks:
      - elastest
  emp-grafana:
    image: grafana/grafana:4.6.1
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=1ccl@b2017
      - GF_SERVER_DOMAIN=nightly.elastest.io:37000
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:/grafana
    networks:
      - elastest
  emp:
    image: elastest/emp:latest
    links:
      - emp-influxdb
      - emp-kafka
    ports:
      - 9100:9000
    environment:
      - STREAM_ADMINUSER=root
      - STREAM_ADMINPASS=pass1234
      - STREAM_DBENDPOINT=emp-influxdb:8086
      - STREAM_ACCESSURL=nightly.elastest.io:37000/influxui
      - STREAM_DBTYPE=influxdb
      - ZOOKEEPER_ENDPOINT=emp-kafka:2181
      - KAFKA_ENDPOINT=emp-kafka:9092
      - TOPIC_CHECK_INTERVAL=30000
      - INFLUX_URL=http://emp-influxdb:8086
      - INFLUX_URL_GRAFANA=http://emp-influxdb:8086
      - GRAFANA_URL=http://emp-grafana:3000
      - GRAFANA_ADMIN=admin
      - GRAFANA_PASSWORD=1ccl@b2017
      - INFLUX_USER=root
      - INFLUX_PASSWORD=pass1234
      - SENTINEL_DB_ENDPOINT=/data/sentinel.db
      - ADMIN_TOKEN=somevalue
      - DASHBOARD_TITLE=elastest
      - DASHBOARD_ENDPOINT=nightly.elastest.io:37000/grafana
      - PROXY_WORKAROUND_ENABLE=false
      - PROXY_WORKAROUND_TYPE=nginx
      - PROXY_WORKAROUND_LOCATION=/emp-admin
      - ET_EDM_ALLUXIO_API=http://edm-alluxio-master:19999/
      - ET_EDM_MYSQL_HOST=edm-mysql
      - ET_EDM_MYSQL_PORT=3306
      - ET_EDM_ELASTICSEARCH_API=http://edm-elasticsearch:9200/
      - ET_EDM_API=http://edm:37003/
      - ET_EPM_API=http://epm:37002/
      - ET_ETM_API=http://etm:37006/
      - ET_ESM_API=http://esm:37005/
      - ET_EIM_API=http://eim:37004/
      - ET_ETM_LSBEATS_HOST=etm-beats
      - ET_ETM_LSBEATS_PORT=5044
      - ET_ETM_LSHTTP_API=http://etm-logstash:5002/
      - ET_ETM_RABBIT_HOST=etm-rabbitmq
      - ET_ETM_RABBIT_PORT=5672
      - ET_EMP_API=http://eim:37001/
      - ET_EMP_INFLUXDB_API=http://emp-influxdb:8086/
      - ET_EMP_INFLUXDB_HOST=emp-influxdb
      - ET_EMP_INFLUXDB_GRAPHITE_PORT=2003
    volumes:
      - emp:/data
    networks:
      - elastest
  emp-system-agent:
    image: elastest/emp-system-agent:latest
    links:
      - emp-kafka
      - emp
    depends_on:
      - emp-kafka
      - emp
    environment:
      - KAFKA_ENDPOINT=emp-kafka:9092
      - KAFKA_KEY_SERIALIZER=StringSerializer
      - KAFKA_VALUE_SERIALIZER=StringSerializer
      - SENTINEL_TOPIC=user-1-elastest_core
      - SENTINEL_SERIES=sys-stats
      - PERIODICITY=60
    networks:
      - elastest
  emp-docker-agent:
    image: elastest/emp-docker-agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    links:
      - emp-kafka
      - emp
    depends_on:
      - emp-kafka
      - emp
    environment:
      - KAFKA_ENDPOINT=emp-kafka:9092
      - KAFKA_KEY_SERIALIZER=StringSerializer
      - KAFKA_VALUE_SERIALIZER=StringSerializer
      - SENTINEL_TOPIC=user-1-elastest_core
      - SENTINEL_SERIES=docker-stats
      - DOCKER_SOCKET=unix://var/run/docker.sock
      - PERIODICITY=120
    networks:
      - elastest
volumes:
  emp:
networks:
    elastest:
        driver: bridge
